# -*- coding: utf-8 -*-
"""nltk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VLgmQ4QVw_uJnCLWJHuOQ9p5DhToUT9N
"""

import urllib.request #handing url
from bs4 import   BeautifulSoup #handling or parsing html file

import nltk #toolkit
nltk.download('stopwords') #for extraction

from nltk.corpus import stopwords

response = urllib.request.urlopen('https://en.wikipedia.org/wiki/SpaceX')
html = response.read()
print (html)

soup = BeautifulSoup(html,'html5lib')
text = soup.get_text(strip=True)
print (text) #no tags real data

tokens = [t for t in text.split()]
print(tokens)

sr= stopwords.words('english')
clean_tokens = tokens[:]
for token in tokens:
  if token in stopwords.words('english'):
    clean_tokens.remove(token)

freq = nltk.FreqDist(clean_tokens)
for key,val in freq.items():
  print(str(key) + ':' + str(val))
freq.plot(30, cumulative=False)